### ISSUE TITLE
Type Error crashes promisify. 

### ISSUE THREAD

**Issue by LibertyBeta** [carlessistare/grpc-promise#2]
With the most recent grpc update the library now crashes with the error

`TypeError: requestTypes[originalFunction.name] is not a function`

**Comment by carlessistare** [comment]
Thanks for the input @LibertyBeta , I'll work on it as soon as possible

**Comment by jordan-nuro** [comment]
I've also run into this issue, thank you for creating this library @carlessistare.

**Comment by jrejaud** [comment]
I've also run into this issue, I am using version `1.4.1` of gRPC's Node dependency.
Thank you for creating this library @carlessistare 
```
TypeError: requestTypes[originalFunction.name] is not a function
    at /.../node_modules/grpc-promise/lib/index.js:6:63
    at Array.forEach (native)
    at Object.promisifyAll (/.../node_modules/grpc-promise/lib/index.js:4:46)
```

**Comment by carlessistare** [comment]
Working on it @jrejaud thanks for your feedback
